2019-12-17 14:14:25,124 - modeltest.py[line:160] - INFO: image:ZB20191114-090306000002.jpg
2019-12-17 14:14:25,625 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDA5Njg5OGU='}}
2019-12-17 14:14:25,913 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:25,919 - modeltest.py[line:160] - INFO: image:ZB20191114-100117000021.jpg
2019-12-17 14:14:25,966 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDA5N2UzNTk='}}
2019-12-17 14:14:26,013 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,021 - modeltest.py[line:160] - INFO: image:ZB20191114-100313000022.jpg
2019-12-17 14:14:26,030 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDA5ODBiOGQ='}}
2019-12-17 14:14:26,098 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,105 - modeltest.py[line:160] - INFO: image:ZB20191114-100349000023.jpg
2019-12-17 14:14:26,130 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDA5OTg0ODg='}}
2019-12-17 14:14:26,196 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,202 - modeltest.py[line:160] - INFO: image:ZB20191114-100630000026.jpg
2019-12-17 14:14:26,210 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDEwMDdiODU='}}
2019-12-17 14:14:26,260 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,266 - modeltest.py[line:160] - INFO: image:ZB20191114-100924000031.jpg
2019-12-17 14:14:26,288 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDEwMTNkZDM='}}
2019-12-17 14:14:26,327 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,334 - modeltest.py[line:160] - INFO: image:ZB20191114-100954000032.jpg
2019-12-17 14:14:26,346 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDEwMmYyY2I='}}
2019-12-17 14:14:26,397 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,402 - modeltest.py[line:160] - INFO: image:ZB20191114-101241000035.jpg
2019-12-17 14:14:26,418 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:WXjNeblDs8gGmuJNMFWMUG1EYoU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyNn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNjAwMDEwM2JmYTU='}}
2019-12-17 14:14:26,484 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,490 - modeltest.py[line:160] - INFO: image:ZB20191114-101325000036.jpg
2019-12-17 14:14:26,500 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwNDM0ZGU='}}
2019-12-17 14:14:26,549 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,555 - modeltest.py[line:160] - INFO: image:ZB20191114-101712000040.jpg
2019-12-17 14:14:26,572 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwNWE3Yzc='}}
2019-12-17 14:14:26,610 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,616 - modeltest.py[line:160] - INFO: image:ZB20191114-101739000041.jpg
2019-12-17 14:14:26,625 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwNjFlNDI='}}
2019-12-17 14:14:26,685 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,691 - modeltest.py[line:160] - INFO: image:ZB20191114-102118000042.jpg
2019-12-17 14:14:26,705 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwN2RjNjA='}}
2019-12-17 14:14:26,776 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,784 - modeltest.py[line:160] - INFO: image:ZB20191114-104245000048.jpg
2019-12-17 14:14:26,798 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwODFiM2M='}}
2019-12-17 14:14:26,850 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,859 - modeltest.py[line:160] - INFO: image:ZB20191114-105813000051.jpg
2019-12-17 14:14:26,888 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDEwOWRmZDA='}}
2019-12-17 14:14:26,924 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:26,931 - modeltest.py[line:160] - INFO: image:ZB20191114-111329000076.jpg
2019-12-17 14:14:26,939 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExMDAwMjY='}}
2019-12-17 14:14:26,993 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,000 - modeltest.py[line:160] - INFO: image:ZB20191114-112316000083.jpg
2019-12-17 14:14:27,010 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExMWViYWM='}}
2019-12-17 14:14:27,051 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,059 - modeltest.py[line:160] - INFO: image:ZB20191114-113635000087.jpg
2019-12-17 14:14:27,069 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExMmQ2YTg='}}
2019-12-17 14:14:27,117 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,124 - modeltest.py[line:160] - INFO: image:ZB20191114-113719000088.jpg
2019-12-17 14:14:27,135 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExM2Q5YmE='}}
2019-12-17 14:14:27,174 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,181 - modeltest.py[line:160] - INFO: image:ZB20191114-114251000092.jpg
2019-12-17 14:14:27,188 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExNDI4MzE='}}
2019-12-17 14:14:27,222 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,229 - modeltest.py[line:160] - INFO: image:ZB20191114-122715000103.jpg
2019-12-17 14:14:27,245 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExNTAxZDA='}}
2019-12-17 14:14:27,295 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,303 - modeltest.py[line:160] - INFO: image:ZB20191114-122751000104.jpg
2019-12-17 14:14:27,315 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExNjQwYjI='}}
2019-12-17 14:14:27,350 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,357 - modeltest.py[line:160] - INFO: image:ZB20191114-124511000106.jpg
2019-12-17 14:14:27,367 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExNzUzNmM='}}
2019-12-17 14:14:27,391 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,398 - modeltest.py[line:160] - INFO: image:ZB20191114-131149000111.jpg
2019-12-17 14:14:27,410 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:HZgHAoYD2fHINYqc4mRYK_0YUs8=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyN30=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyNzAwMDExOGY4MzQ='}}
2019-12-17 14:14:27,447 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,456 - modeltest.py[line:160] - INFO: image:ZB20191114-131207000112.jpg
2019-12-17 14:14:27,479 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:jI00H9h-gHI9EE-QFW9cUWFV2AU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyODAwMDExOTY0ZDk='}}
2019-12-17 14:14:27,508 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,515 - modeltest.py[line:160] - INFO: image:ZB20191114-132052000115.jpg
2019-12-17 14:14:27,706 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:jI00H9h-gHI9EE-QFW9cUWFV2AU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyODAwMDEyMDI1MjI='}}
2019-12-17 14:14:27,734 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,741 - modeltest.py[line:160] - INFO: image:ZB20191114-132518000117.jpg
2019-12-17 14:14:27,906 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:jI00H9h-gHI9EE-QFW9cUWFV2AU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyODAwMDEyMTZmMWM='}}
2019-12-17 14:14:27,931 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:27,939 - modeltest.py[line:160] - INFO: image:ZB20191114-133653000118.jpg
2019-12-17 14:14:28,059 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:jI00H9h-gHI9EE-QFW9cUWFV2AU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyODAwMDEyMjBhZGM='}}
2019-12-17 14:14:28,084 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,091 - modeltest.py[line:160] - INFO: image:ZB20191114-143512000120.jpg
2019-12-17 14:14:28,426 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:jI00H9h-gHI9EE-QFW9cUWFV2AU=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyODAwMDEyM2M3M2M='}}
2019-12-17 14:14:28,454 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,461 - modeltest.py[line:160] - INFO: image:ZB20191114-161923000122.jpg
2019-12-17 14:14:28,470 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyNDRlMDg='}}
2019-12-17 14:14:28,495 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,503 - modeltest.py[line:160] - INFO: image:ZB20191114-163942000126.jpg
2019-12-17 14:14:28,517 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyNTk2YTA='}}
2019-12-17 14:14:28,550 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,558 - modeltest.py[line:160] - INFO: image:ZB20191114-164845000130.jpg
2019-12-17 14:14:28,568 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyNmMwNzM='}}
2019-12-17 14:14:28,607 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,615 - modeltest.py[line:160] - INFO: image:ZB20191114-224222000148.jpg
2019-12-17 14:14:28,628 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyNzg0Y2Y='}}
2019-12-17 14:14:28,655 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,663 - modeltest.py[line:160] - INFO: image:ZB20191115-090422000001.jpg
2019-12-17 14:14:28,703 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyODQ3ZGY='}}
2019-12-17 14:14:28,731 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,742 - modeltest.py[line:160] - INFO: image:ZB20191115-194339000013.jpg
2019-12-17 14:14:28,759 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEyOTUwODA='}}
2019-12-17 14:14:28,801 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,808 - modeltest.py[line:160] - INFO: image:ZB20191115-201540000014.jpg
2019-12-17 14:14:28,823 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzMDlmNWQ='}}
2019-12-17 14:14:28,863 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,872 - modeltest.py[line:160] - INFO: image:ZB20191115-214620000015.jpg
2019-12-17 14:14:28,883 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzMTZkOTk='}}
2019-12-17 14:14:28,908 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,915 - modeltest.py[line:160] - INFO: image:ZB20191115-222414000016.jpg
2019-12-17 14:14:28,923 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzMjk5NGU='}}
2019-12-17 14:14:28,956 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:28,964 - modeltest.py[line:160] - INFO: image:ZB20191116-112221000002.jpg
2019-12-17 14:14:28,974 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzM2I1MzU='}}
2019-12-17 14:14:29,024 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,030 - modeltest.py[line:160] - INFO: image:ZB20191116-115454000004.jpg
2019-12-17 14:14:29,039 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzNDVjNzc='}}
2019-12-17 14:14:29,066 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,075 - modeltest.py[line:160] - INFO: image:ZB20191117-223641000002.jpg
2019-12-17 14:14:29,097 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzNWIzZWY='}}
2019-12-17 14:14:29,125 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,132 - modeltest.py[line:160] - INFO: image:ZB20191118-100804000002.jpg
2019-12-17 14:14:29,140 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzNmNkOTc='}}
2019-12-17 14:14:29,172 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,181 - modeltest.py[line:160] - INFO: image:ZB20191118-173739000003.jpg
2019-12-17 14:14:29,205 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzNzBmYTA='}}
2019-12-17 14:14:29,234 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,241 - modeltest.py[line:160] - INFO: image:ZB20191118-175932000004.jpg
2019-12-17 14:14:29,249 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzOGZmZTY='}}
2019-12-17 14:14:29,277 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,285 - modeltest.py[line:160] - INFO: image:ZB20191119-104032000005.jpg
2019-12-17 14:14:29,297 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDEzOTQxNmU='}}
2019-12-17 14:14:29,326 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,333 - modeltest.py[line:160] - INFO: image:ZB20191119-160645000011.jpg
2019-12-17 14:14:29,342 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDE0MDZiZmY='}}
2019-12-17 14:14:29,372 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,380 - modeltest.py[line:160] - INFO: image:ZB20191119-162353000012.jpg
2019-12-17 14:14:29,436 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tl0tYxAzbK8ok_jM6zcSFO5h_0Y=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMyOX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDoyOTAwMDE0MWZlZDU='}}
2019-12-17 14:14:29,464 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,472 - modeltest.py[line:160] - INFO: image:ZB20191120-135617000002.jpg
2019-12-17 14:14:29,486 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0MjBhZTE='}}
2019-12-17 14:14:29,515 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,526 - modeltest.py[line:160] - INFO: image:ZB20191120-150358000004.jpg
2019-12-17 14:14:29,561 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0M2JjODA='}}
2019-12-17 14:14:29,590 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,597 - modeltest.py[line:160] - INFO: image:ZB20191120-155104000007.jpg
2019-12-17 14:14:29,613 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0NDA2MmM='}}
2019-12-17 14:14:29,642 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,649 - modeltest.py[line:160] - INFO: image:ZB20191120-164307000010.jpg
2019-12-17 14:14:29,686 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0NWE2ZmY='}}
2019-12-17 14:14:29,716 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,724 - modeltest.py[line:160] - INFO: image:ZB20191120-171256000015.jpg
2019-12-17 14:14:29,733 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0NjlkZGU='}}
2019-12-17 14:14:29,775 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,782 - modeltest.py[line:160] - INFO: image:ZB20191120-181507000018.jpg
2019-12-17 14:14:29,811 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0N2I1YWE='}}
2019-12-17 14:14:29,837 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,844 - modeltest.py[line:160] - INFO: image:ZB20191120-181603000020.jpg
2019-12-17 14:14:29,863 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0ODJiZDU='}}
2019-12-17 14:14:29,889 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,896 - modeltest.py[line:160] - INFO: image:ZB20191122-105649000002.jpg
2019-12-17 14:14:29,931 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE0OWM2NmU='}}
2019-12-17 14:14:29,963 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:29,972 - modeltest.py[line:160] - INFO: image:ZB20191122-141822000006.jpg
2019-12-17 14:14:29,981 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE1MGQ5NDY='}}
2019-12-17 14:14:30,008 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,016 - modeltest.py[line:160] - INFO: image:ZB20191122-163811000013.jpg
2019-12-17 14:14:30,040 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE1MTNmYWY='}}
2019-12-17 14:14:30,068 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,075 - modeltest.py[line:160] - INFO: image:ZB20191122-172101000014.jpg
2019-12-17 14:14:30,283 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE1MjA0MTU='}}
2019-12-17 14:14:30,321 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,327 - modeltest.py[line:160] - INFO: image:ZB20191123-195246000001.jpg
2019-12-17 14:14:30,343 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:EioZhiE8ICHiFFXjC5brNrjagK4=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMH0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMDAwMDE1MzFiN2I='}}
2019-12-17 14:14:30,371 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,379 - modeltest.py[line:160] - INFO: image:ZB20191124-220845000010.jpg
2019-12-17 14:14:30,650 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1NGExZTE='}}
2019-12-17 14:14:30,679 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,697 - modeltest.py[line:160] - INFO: image:ZB20191125-150851000008.jpg
2019-12-17 14:14:30,755 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1NTliYTY='}}
2019-12-17 14:14:30,798 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,805 - modeltest.py[line:160] - INFO: image:ZB20191125-160830000009.jpg
2019-12-17 14:14:30,815 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1NmNiYWI='}}
2019-12-17 14:14:30,845 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:30,852 - modeltest.py[line:160] - INFO: image:ZB20191125-162020000010.jpg
2019-12-17 14:14:31,195 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1NzE2N2Y='}}
2019-12-17 14:14:31,227 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,234 - modeltest.py[line:160] - INFO: image:ZB20191125-170535000011.jpg
2019-12-17 14:14:31,248 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1ODhjMTA='}}
2019-12-17 14:14:31,275 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,282 - modeltest.py[line:160] - INFO: image:ZB20191126-112716000001.jpg
2019-12-17 14:14:31,315 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE1OWZjYjg='}}
2019-12-17 14:14:31,342 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,349 - modeltest.py[line:160] - INFO: image:ZB20191127-121706000005.jpg
2019-12-17 14:14:31,358 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE2MGEyYmY='}}
2019-12-17 14:14:31,384 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,392 - modeltest.py[line:160] - INFO: image:ZB20191127-200734000011.jpg
2019-12-17 14:14:31,403 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE2MTEzNzM='}}
2019-12-17 14:14:31,446 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,455 - modeltest.py[line:160] - INFO: image:ZB20191127-211825000017.jpg
2019-12-17 14:14:31,468 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:tYb69d60mc4KUmff6qMIwalFDgo=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMX0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMTAwMDE2MjNlZTg='}}
2019-12-17 14:14:31,498 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,508 - modeltest.py[line:160] - INFO: image:ZB20191127-211856000018.jpg
2019-12-17 14:14:31,518 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2MzFhOGM='}}
2019-12-17 14:14:31,567 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,575 - modeltest.py[line:160] - INFO: image:ZB20191128-170406000003.jpg
2019-12-17 14:14:31,584 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2NGE1YzA='}}
2019-12-17 14:14:31,612 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,620 - modeltest.py[line:160] - INFO: image:ZB20191128-205616000009.jpg
2019-12-17 14:14:31,630 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2NWFhNTc='}}
2019-12-17 14:14:31,658 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,666 - modeltest.py[line:160] - INFO: image:ZB20191128-210040000010.jpg
2019-12-17 14:14:31,696 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2NjhlYTQ='}}
2019-12-17 14:14:31,723 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,732 - modeltest.py[line:160] - INFO: image:ZB20191128-210431000011.jpg
2019-12-17 14:14:31,744 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2N2MwZDA='}}
2019-12-17 14:14:31,770 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,777 - modeltest.py[line:160] - INFO: image:ZB20191129-103359000013.jpg
2019-12-17 14:14:31,786 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2ODA4Y2Y='}}
2019-12-17 14:14:31,814 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,823 - modeltest.py[line:160] - INFO: image:ZB20191130-171801000003.jpg
2019-12-17 14:14:31,834 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE2OWZkMmQ='}}
2019-12-17 14:14:31,870 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,879 - modeltest.py[line:160] - INFO: image:ZB20191130-185034000008.jpg
2019-12-17 14:14:31,892 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3MDRmNDQ='}}
2019-12-17 14:14:31,923 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,932 - modeltest.py[line:160] - INFO: image:ZB20191203-14121100000144b4.jpg
2019-12-17 14:14:31,945 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3MTYwMTc='}}
2019-12-17 14:14:31,972 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:31,979 - modeltest.py[line:160] - INFO: image:ZB20191204-22102000000298c8.jpg
2019-12-17 14:14:31,989 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3MjA4ZjI='}}
2019-12-17 14:14:32,015 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,022 - modeltest.py[line:160] - INFO: image:ZB20191209-102929000003d578.jpg
2019-12-17 14:14:32,043 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3MzIwOWQ='}}
2019-12-17 14:14:32,072 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,081 - modeltest.py[line:160] - INFO: image:ZB20191209-1547310000059d33.jpg
2019-12-17 14:14:32,092 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3NGRkNGM='}}
2019-12-17 14:14:32,123 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,131 - modeltest.py[line:160] - INFO: image:ZB20191210-203411000001ff21.jpg
2019-12-17 14:14:32,141 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3NTc0MzU='}}
2019-12-17 14:14:32,173 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,181 - modeltest.py[line:160] - INFO: image:ZB20191210-203750000002db69.jpg
2019-12-17 14:14:32,189 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3NjlkMWM='}}
2019-12-17 14:14:32,222 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,228 - modeltest.py[line:160] - INFO: image:ZB20191211-101347000001b911.jpg
2019-12-17 14:14:32,242 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3NzE4ZDE='}}
2019-12-17 14:14:32,268 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,278 - modeltest.py[line:160] - INFO: image:ZB20191211-10225200000204d6.jpg
2019-12-17 14:14:32,287 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3ODljMzY='}}
2019-12-17 14:14:32,323 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,332 - modeltest.py[line:160] - INFO: image:ZB20191213-150612000008cf65.jpg
2019-12-17 14:14:32,343 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE3OWY4NWY='}}
2019-12-17 14:14:32,370 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2019-12-17 14:14:32,378 - modeltest.py[line:160] - INFO: image:ZB20191215-105220000001ed71.jpg
2019-12-17 14:14:32,389 - modeltest.py[line:26] - INFO: {'code': '0000', 'desc': '请求成功', 'data': {'qiNiuToken': 'kbZyUO0zdM8jvbdoWCqsjv8VjvrgKXIhewyaDXto:vbf7VjF5x5z_Z0juUq6vIw2iZtk=:eyJzY29wZSI6ImRldi1waG90b3MiLCJkZWFkbGluZSI6MTU3NjU2MzMzMn0=', 'key': 'UkIyMDE5MTIxNy0xNDoxNDozMjAwMDE4MDUzMDA='}}
2019-12-17 14:14:32,414 - modeltest.py[line:168] - ERROR: HTTPSConnectionPool(host='upload-z2.qiniup.com', port=443): Max retries exceeded with url: /putb64/-1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
